=== dark-carbon-code/CyoTE-Tool-Wiz/schema/tool_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "CyOTE Tool Capability",
    "type": "object",
    "required": ["tool_name", "description", "user_roles", "tactics_supported", "techniques_supported"],
    "properties": {
      "tool_name": { "type": "string" },
      "description": { "type": "string" },
      "user_roles": {
        "type": "array",
        "items": { "type": "string" }
      },
      "tactics_supported": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "matrix": { "type": "string", "enum": ["Enterprise", "ICS"] }
          },
          "required": ["name", "matrix"]
        }
      },
      "techniques_supported": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": { "type": "string" },
            "name": { "type": "string" },
            "matrix": { "type": "string", "enum": ["Enterprise", "ICS"] }
          },
          "required": ["id", "name", "matrix"]
        }
      },
      "observable_types": {
        "type": "array",
        "items": { "type": "string" }
      },
      "use_cases": {
        "type": "array",
        "items": { "type": "string" }
      },
      "data_sources": {
        "type": "array",
        "items": { "type": "string" }
      },
      "deployment_context": { "type": "string" },
      "example_usage": { "type": "string" },
      "github": { "type": "string" },
      "factsheet": { "type": "string" }
    }
  }

=== dark-carbon-code/CyoTE-Tool-Wiz/data/tool_capabilities/BAM_20250604203529.json
{
  "tool_name": "BAM",
  "description": "identify likelihood of adversarial behavior",
  "user_roles": [],
  "tactics_supported": [],
  "techniques_supported": [],
  "observable_types": [],
  "use_cases": [
    "Anomaly Detection",
    "Cyber Intelligence"
  ],
  "data_sources": [],
  "deployment_context": "FastAPI endpoint, Linux host, Windows Host",
  "example_usage": "Help users determine if an anomaly is related to cyber-based adversary behavior",
  "github": "inl.gov/BAM",
  "factsheet": "inl.gov/BAM"
}
